### Variáveis de Ambiente
@hostname = localhost
@port = 80
@host = {{hostname}}:{{port}}
@contentType = application/json
@token= CfgE2wi+mVcgMAFvy0T+JomFr6k/l1bVz9/p2SgWYxs=

### 1. Criar um Novo Utilizador
POST http://{{host}}/api/users
Content-Type: {{contentType}}

{
    "name": "Bananinha",
    "email": "carolbrazete10@gmail.com",
    "password": "Carol2010!"
}

### 2. Login (Obter Token e Set-Cookie)
POST http://{{host}}/api/users/token
Content-Type: {{contentType}}

{
    "email": "a51661@alunos.isel.pt",
    "password": "Carolzinha2010!"
}

### 3. Logout 
POST http://{{host}}/api/users/logout
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### 4. getCountries 
GET http://{{host}}/api/getCountries
Authorization: Bearer {{token}}
Content-Type: {{contentType}}



### Get user info
GET http://{{host}}/api/users/27
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get my info
GET http://{{host}}/api/users/profile/me
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### CheckCreatorOrCompany
GET http://{{host}}/api/users/profile/CheckCreatorOrCompany
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### 5. Editar user
POST http://{{host}}/api/users/edit
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "newUsername": "banana"
}

### 5. Editar password
POST http://{{host}}/api/users/changePassword
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "OldPassword": "PasswordSegura123",
    "NewPassword": "PassworInsegura123"
}


### 6. Verificar Email //quando email nao existe dá 500 e nao devia
POST http://{{host}}/api/users/verifyEmail
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "email": "carolbrazete10@gmail.com",
    "code": "257882" 
}

### 7. Reenviar Confirmação de Email
POST http://{{host}}/api/users/resendEmailConfirmation
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "email": "Bananinha1234@example.com"
}

### Register Creator
POST http://{{host}}/api/creator
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "artisticName": "Kazio"
}

### Get creator info
GET http://{{host}}/api/creator/42
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


//dá null no sector e no subsector sempre que se cria uma company, com 200
### Register Company
POST http://{{host}}/api/company
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "CompanySize": 1000,
  "CompanyName": "carolzinhaCompany",
  "Description": "é isso",
  "Sectors": [
    "Education & E-learning",
    "Technology & SaaS",
    "Sustainability & Ecology",
    "Travel & Tourism",
    "Finance & Fintech",
    "Sports & Fitness",
    "Real Estate",
    "Automotive & Mobility",
    "Children & Maternity",
    "Pets",
    "Marketing & Advertising",
    "Retail & E-commerce",
    "Events & Lifestyle"
  ],
  "WebsiteLink": "https://fr.primor.eu/fr_fr/",
  "CountryHeadquarters": "France"
}

### Rate Creator
POST http://{{host}}/api/creator/rateCreator/20
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "Rate": 1
}

### Get my rate on a creator
GET http://{{host}}/api/creators/20/my-rating
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Change Status
POST http://{{host}}/api/creator/status
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "AvailabilityStatus": "UNAVAILABLE"
}

### Edit Creator
POST http://{{host}}/api/creator/edit
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "ArtisticName": "CarolininhaFofa"
}

### Edit Company Profile
POST http://{{host}}/api/company/edit
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "CompanySize": 200000,
  "CompanyName": "Hublizinho",
  "Description": "Adoro o que faço",
  "Sectors": ["Automotive & Mobility"],
  "WebsiteLink": "http://www.bananinha.ed",
  "CountryHeadquarters": "Spain"
}


### Get company info
GET http://{{host}}/api/company/5
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### ver historico de pesquisas
GET http://{{host}}/api/users/getHistory
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

########################## Search companies ##########################

### 
GET http://{{host}}/api/company?page=1&pageSize=5
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### deveria de funcionar melhor com pesquisas minusculas
GET http://{{host}}/api/company?name=ha
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/company?companySize=0%20a%20100
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/company?Countries=portugal&Countries=spain
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### 
GET http://{{host}}/api/company?Sectors=Technology%20%26%20SaaS&page=1&pageSize=5
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

##############################################################################

### Criar SocialProfile do creator
POST http://{{host}}/api/creator/socialProfile
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "Platform_user_name": "caroli",
  "Link": "https://www.youtube.com/@KazzioProva",
  "Description": "Adoro fazer pranks",
  "Followers_count": 4,
  "PriceMin": 10.00,
  "PriceMax": 20.00,  
  "PlatformId": 3,
  "Sectors": ["Automotive & Mobility", "Pets"]
}

### Get all platforms
GET http://{{host}}/api/socialPlatform
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### apagar platform do creator
DELETE http://{{host}}/api/creator/socialProfile/23
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get platform do creator
GET http://{{host}}/api/creator/socialProfile/11
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Edit CreateSocialProfile erro 500 quando tentamos edi
POST http://{{host}}/api/creator/socialProfile/edit/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "PlatformUserName": "abfiuabw",
  "Link": "https://www.youtube.com/@titio",
  "Description": "Afinal nao adoro assim tanto fazer pranks",
  "Sectors": ["Automotive & Mobility", "Pets", "Real Estate"],
  "FollowersCount": 1,
  "PriceMin": 10.00,
  "PriceMax": 70.00
}

### Obter todos os sectores disponíveis
GET http://{{host}}/api/sectors
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

########################## Search creators ##########################

### 
GET http://{{host}}/api/creators?page=1&pageSize=10
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### deveria de funcionar melhor com pesquisas minusculas
GET http://{{host}}/api/creators?PlatformUserName=elena
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/creators?companySize=0%20a%20100
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/creators?Countries=portugal&Countries=spain
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### 
GET http://{{host}}/api/creators?Sectors=Entertainment%20%26%20Media&page=1&pageSize=5
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Get Trending Creators (Top 15 mais visualizados)
GET http://{{host}}/api/creator/trending
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get Trending Company (Top 15 mais visualizados)
GET http://{{host}}/api/company/trending
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

##############################################################################

### Get full Creator profile
GET http://{{host}}/api/users/42/fullCreatorProfile
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Get full Company profile
GET http://{{host}}/api/users/34/fullCompanyProfile
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Apagar Social Profile do Creator
DELETE http://{{host}}/api/creator/socialProfile/29
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

##############################################################################

### Create Chat Conversation
POST  http://{{host}}/api/conversation
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "Sender": {
    "ProfileId": 23,
    "Type": 2
  },
  "Receiver": {
    "ProfileId": 43,
    "Type": 1
  } 
}

### Send a message
POST  http://{{host}}/api/conversation/1/message
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Olá! Tudo bem?"
}

### Edit a message
POST  http://{{host}}/api/conversation/message/edit/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Olá Como te chamas?"
}

### Delete a Message
DELETE http://{{host}}/api/conversation/message/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Get Messages (Paginated)
GET http://{{host}}/api/conversation/2/messages?page=1&pageSize=100
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Get My Conversations Creator (List of conversations with last message and timestamp)
GET http://{{host}}/api/conversation/23/my-conversations
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get My Conversations Company (List of conversations with last message and timestamp)
GET http://{{host}}/api/conversation/43/company-conversations
Authorization: Bearer {{token}}
Content-Type: {{contentType}}



### Get Recommended Companies (Baseado no histórico e scoring)
GET http://{{host}}/api/company/getRecommendations
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Get Recommended Creators (Baseado no histórico e scoring)
GET http://{{host}}/api/creators/getRecommendations
Authorization: Bearer {{token}}
Content-Type: {{contentType}}
