### Variáveis de Ambiente
@hostname = localhost
@port = 80
@host = {{hostname}}:{{port}}
@contentType = application/json
@token= WwozQs7xxVHfNDiYrmbQo9rR18WV5xKBvG3APdHLioU=

### 1. Criar um Novo Utilizador
POST http://{{host}}/api/users
Content-Type: {{contentType}}

{
    "name": "Bananinha",
    "email": "Bananinha1235@example.com",
    "password": "PasswordSegura123"
}

### 2. Login (Obter Token e Set-Cookie)
POST http://{{host}}/api/users/token
Content-Type: {{contentType}}

{
    "email": "Bananinha1235@example.com",
    "password": "PasswordSegura123"
}

### 3. Logout 
POST http://{{host}}/api/users/logout
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get user info
GET http://{{host}}/api/users/2
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get my info
GET http://{{host}}/api/users/profile/me
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### 5. Editar user
POST http://{{host}}/api/users/edit
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "newUsername": "banana"
}

### 5. Editar password
POST http://{{host}}/api/users/changePassword
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "OldPassword": "PasswordSegura123",
    "NewPassword": "PassworInsegura123"
}


### 6. Verificar Email
POST http://{{host}}/api/users/verifyEmail
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "email": "Bananinha1235@example.com",
    "code": "081232" 
}

### 7. Reenviar Confirmação de Email
POST http://{{host}}/api/users/resendEmailConfirmation
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "email": "Bananinha1234@example.com"
}

### Register Creator
POST http://{{host}}/api/creator
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "artisticName": "Kazio"
}

### Register Company
POST http://{{host}}/api/company
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "CompanySize": 1000,
  "CompanyName": "Primor",
  "Description": "This is the world largest company",
  "Sector": "Beauty",
  "WebsiteLink": "https://fr.primor.eu/fr_fr/",
  "CountryHeadquarters": "France"
}


### Register Creator
POST http://{{host}}/api/creator/rateCreator/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "Rate": 5
}

### Change Status
POST http://{{host}}/api/creator/status
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "AvailabilityStatus": "AVAILABLE"
}

### Edit Company Profile
POST http://{{host}}/api/company/edit
Authorization: Bearer {Q{token}}
Content-Type: {{contentType}}

{
  "CompanySize": 200000,
  "CompanyName": "Hublizinho",
  "Description": "Adoro o que faço",
  "Sector": "hubly",
  "WebsiteLink": "http://www.bananinha.ed",
  "CountryHeadquarters": "Spain"
}

##n esta a funcionar
### Get company info
GET http://{{host}}/api/company/1
Content-Type: {{contentType}}

### 
GET http://{{host}}/api/companies?page=1&pageSize=10
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/companies?name=Hub&sector=Beauty
Content-Type: {{contentType}}
###
GET http://{{host}}/api/companies?companySize=100%20a%201000
Content-Type: {{contentType}}
###
GET http://{{host}}/api/companies?countryHeadquarters=Portugal
Content-Type: {{contentType}}
###
GET http://{{host}}/api/companies?name=Primor&sector=Beauty&page=1&pageSize=5
Content-Type: {{contentType}}
