### Variáveis de Ambiente
@hostname = localhost
@port = 80
@host = {{hostname}}:{{port}}
@contentType = application/json
@token= 8lqbgIPvDU4OAyQbZuBNpDlCMYfFMknYADuxvliGGqQ=

### 1. Criar um Novo Utilizador
POST http://{{host}}/api/users
Content-Type: {{contentType}}

{
    "name": "Bananinha",
    "email": "Carolzinha0121@example.com",
    "password": "PasswordSegura123"
}

### 2. Login (Obter Token e Set-Cookie)
POST http://{{host}}/api/users/token
Content-Type: {{contentType}}

{
    "email": "Carolzinha0121@example.com",
    "password": "PasswordSegura123"
}

### 3. Logout 
POST http://{{host}}/api/users/logout
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get user info
GET http://{{host}}/api/users/2
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get my info
GET http://{{host}}/api/users/profile/me
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### 5. Editar user
POST http://{{host}}/api/users/edit
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "newUsername": "banana"
}

### 5. Editar password
POST http://{{host}}/api/users/changePassword
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "OldPassword": "PasswordSegura123",
    "NewPassword": "PassworInsegura123"
}


### 6. Verificar Email
POST http://{{host}}/api/users/verifyEmail
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "email": "Carolzinha0121@example.com",
    "code": "042577" 
}

### 7. Reenviar Confirmação de Email
POST http://{{host}}/api/users/resendEmailConfirmation
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "email": "Bananinha1234@example.com"
}

### Register Creator
POST http://{{host}}/api/creator
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "artisticName": "Kazio"
}

### Get creator info
GET http://{{host}}/api/creator/34
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


// dá erro 500 com o pais errado
// dá erro 500 com o link errado
### Register Company
POST http://{{host}}/api/company
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "CompanySize": 1000,
  "CompanyName": "Fuck",
  "Description": "é isso",
  "WebsiteLink": "https://fr.primor.eu/fr_fr/",
  "CountryHeadquarters": "France"
}


### Rate Creator
POST http://{{host}}/api/creator/rateCreator/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "Rate": 5
}

### Change Status
POST http://{{host}}/api/creator/status
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "AvailabilityStatus": "AVAILABLE"
}

### Edit Company Profile
POST http://{{host}}/api/company/edit
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "CompanySize": 200000,
  "CompanyName": "Hublizinho",
  "Description": "Adoro o que faço",
  "Sectors": ["Automotive & Mobility"],
  "WebsiteLink": "http://www.bananinha.ed",
  "CountryHeadquarters": "Spain"
}


### Get company info
GET http://{{host}}/api/company/34
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### ver historico de pesquisas
GET http://{{host}}/api/users/getHistory
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

########################## Search companies ##########################

### 
GET http://{{host}}/api/companies?page=1&pageSize=10
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### deveria de funcionar melhor com pesquisas minusculas
GET http://{{host}}/api/companies?name=ma
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/companies?companySize=0%20a%20100
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/companies?Countries=portugal&Countries=spain
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### 
GET http://{{host}}/api/companies?Sectors=Technology%20%26%20SaaS&page=1&pageSize=5
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

##############################################################################

### Criar SocialProfile do creator
POST http://{{host}}/api/creator/socialProfile
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "Platform_user_name": "Kazoziiii",
  "Link": "https://www.youtube.com/@KazzioProva",
  "Description": "Adoro fazer pranks",
  "Followers_count": 4,
  "PriceMin": 10.00,
  "PriceMax": 20.00,  
  "PlatformId": 2,
  "Sectors": ["Automotive & Mobility", "Pets"]
}

### Get all platforms
GET http://{{host}}/api/socialPlatform
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### apagar platform do creator
DELETE http://{{host}}/api/creator/socialProfile/2
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Get platform do creator
GET http://{{host}}/api/creator/socialProfile/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### Edit CreateSocialProfile erro 500 quando tentamos edi
POST http://{{host}}/api/creator/socialProfile/edit/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "PlatformUserName": "abfiuabw",
  "Link": "https://www.youtube.com/@titio",
  "Description": "Afinal nao adoro assim tanto fazer pranks",
  "Sectors": ["Automotive & Mobility", "Pets", "Real Estate"],
  "FollowersCount": 1,
  "PriceMin": 10.00,
  "PriceMax": 70.00
}

### Obter todos os sectores disponíveis
GET http://{{host}}/api/sectors
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

########################## Search creators ##########################

### 
GET http://{{host}}/api/creators?page=1&pageSize=10
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### deveria de funcionar melhor com pesquisas minusculas
GET http://{{host}}/api/creators?PlatformUserName=kaz
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/creators?companySize=0%20a%20100
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
GET http://{{host}}/api/creators?Countries=portugal&Countries=spain
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### 
GET http://{{host}}/api/creators?Sectors=Technology%20%26%20SaaS&page=1&pageSize=5
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

##############################################################################