FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app
# Copia o ficheiro da solution e os projetos
COPY *.sln .
COPY Hubly.Api/*.csproj Hubly.Api/
COPY Hubly.Domain/*.csproj Hubly.Domain/
COPY Hubly.Services/*.csproj Hubly.Services/
COPY Hubly.Infrastructure/*.csproj Hubly.Infrastructure/

RUN dotnet restore

# Comando para desenvolvimento com Hot Reload
ENTRYPOINT ["dotnet", "watch", "run", "--project", "Hubly.Api/Hubly.Api.csproj", "--urls", "http://+:8080"]